<template>
  <div>
    <div class="box">
      <div class="timerColor"></div>
      <!-- <el-button @click="add"></el-button> -->
    </div>
  </div>
</template>

<script>
// 引入封装的格式化时间
import { formatTime } from "../ulit/dateTime";
export default {
  
  data() {
    return {
      value: `<p>vue - admin - dome。</p>`,
      date: "",
      timer: "",
      isDialogShow:false,
      formData:{}
    };
  },
  methods: {
    add(){
      
    }
  },
  mounted() {
    setTimeout(() => {
      this.timer = setInterval(() => {
        this.date = formatTime(new Date(), "yyyy-MM-dd hh:mm:ss");
      }, 1000);
    }, 2000);
  },
  beforeDestroy() {
    //清除定时器
    clearInterval(this.timer);
  }
};
</script>

<style lang="scss" scoped>
.box {
  width: 100%;
  position: relative;
}

.timerColor {
  color: #ccc;
  margin-top: 10px;
  width: 200px;
  height: 80px;
  background-color: rgb(202, 157, 157);
  margin: auto;
  animation: vibrate-3 0.5s linear infinite both;
}
/* ----------------------------------------------
 * Generated by Animista on 2020-8-12 16:23:20
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation vibrate-3
 * ----------------------------------------
 */
@keyframes vibrate-3 {
  0% {
    transform: translate(0);
  }
  10% {
    transform: translate(-2px, -2px);
  }
  20% {
    transform: translate(2px, -2px);
  }
  30% {
    transform: translate(-2px, 2px);
  }
  40% {
    transform: translate(2px, 2px);
  }
  50% {
    transform: translate(-2px, -2px);
  }
  60% {
    transform: translate(2px, -2px);
  }
  70% {
    transform: translate(-2px, 2px);
  }
  80% {
    transform: translate(-2px, -2px);
  }
  90% {
    transform: translate(2px, -2px);
  }
  100% {
    transform: translate(0);
  }
}

</style>